name: GemPuzzle
main: de.craften.plugins.gempuzzle.Plugin
version: VERSION
softdepend: [GemApi]
commands:
  gempuzzle:
    description: Create or remove gem puzzles.
    usage: /gempuzzle create to create puzzles, /gempuzzle remove to remove puzzles
permissions:
  gempuzzle.manage:
    default: op
    description: Permission to create and remove gem puzzles.