name: GemPuzzle
main: de.craften.plugins.gempuzzle.Plugin
version: VERSION
commands:
  gempuzzle:
    description: Create and remove gem puzzles.
    usage: /gempuzzle create to create puzzles, /gempuzzle remove to remove puzzles
    permission: gempuzzle.manage
permissions:
  gempuzzle.manage:
    default: op
    description: Permission to create and remove gem puzzles.